install: "npm install uglify-js"
script: "ruby build.rb"
deploy:
  provider: releases
  api-key: "b12c404a97d95a967cdc5a3fdf421db46afc6787"
  file: "ajax.min.js"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
